version: '3'
services:
  nginx:
    image: ubuntu/nginx:1.18-20.04_beta
    container_name: mnx
    build: 
     context: .
     dockerfile: Dockerfile
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./backend/sites-available:/etc/nginx/sites-available
      - ./backend/html:/var/www/html
      - ./backend/board:/var/www/board
      - ./backend/logs:/var/log/nginx