const fs = require('fs')
const env = process.env

function _main_() {
    const _path = `${env.PWD}/src/assets/source/icons`
    const list = fs.readdirSync(_path)
    _mkNames(list)
    let result = '<svg xmlns="http://www.w3.org/2000/svg">'
    const rgx = /<svg.*?\>(.*?)\<\/svg\>/g

    for (const item of list) {
        const _name = item.replace('.svg', '')
        const current = fs.readFileSync(`${_path}/${item}`, 'utf-8')
        const parts = current.matchAll(rgx)
        const selected = [...parts][0][1]
        const comp = `<symbol id="${_name}" xmlns="http://www.w3.org/2000/svg">${selected}</symbol>`
        result += comp
    }
    result += '</svg>'
    fs.writeFileSync(`${env.PWD}/src/assets/icons/icon-sprite.svg`, result)

    console.log('result terminated')
}
function _mkNames(list) {
    let str = '// Autogenerated file run "yarn mk-icons"\n\nexport const IconNames = [\n'
    for (const item of list) {
        const nstr = item.replace('.svg', '')
        str += `'${nstr}',\n`
    }

    str += ']\n\nexport type IconNames = typeof IconNames[number]\n'

    fs.writeFileSync(`${env.PWD}/src/components/Icon/IconNames.ts`, str)
    console.log('File "IconNames.ts" created successfully')
}

_main_()
