// Autogenerated file run "yarn mk-images"

export const imageRepository = {
    'landing:landingPage.poster1': 'http://localhost/_assets_server/images/cerro/cerro-panoramic-dron.jpg',
    'landing:landingPage.poster': 'http://127.0.0.1:3000/static/images/cerro/desert.jpg',
    'personnel:profile.pepe': '/_assets_server/images/personnel/pepe.jpg',
}

export type iKeyNames = 'landing:landingPage.poster1' | 'landing:landingPage.poster' | 'personnel:profile.pepe'
