// Autogenerated file run "yarn mk-locales"

export const validTranslationKeys = {
    en: {
        'academy:frontPage.title': 'Bienvenido a la Academia mecuate astrophytum',
        'academy:frontPage.description': 'this academy is made for all peoples from anywhrer in the universe.',
        'academy:workShopPage.groupName': 'Nombre de Grupo',
        'academy:workShopPage.groupType.solid': 'Grupo sólido',
        'academy:workShopPage.groupType.stable': 'Grupo fijo',
        'academy:workShopPage.groupType.morph': 'Grupo Anomórfico',
        'common:menu.home': 'home',
        'common:menu.mecuate': 'Mecuate',
        'common:menu.account': 'My Account',
        'common:menu.academy': 'Academy',
        'common:menu.services': 'Services',
        'common:menu.docuweb': 'DocuWeb',
        'common:menu.projects': 'Projects',
        'common:menu.publications': 'Publications',
        'common:menu.contact': 'Contact',
        'common:menu.production': 'Production',
        'common:sections.previousWorkShops': 'Previous',
        'common:sections.nextWorkShops': 'Comming next',
        'common:sections.currentWorkShops': 'Current',
        'common:sections.blog': 'Other media',
    },
    es: {
        'academy:frontPage.title': 'Bienvenido a la Academia mecuate astrophytum',
        'academy:frontPage.description': 'this academy is made for all peoples from anywhrer in the universe.',
        'academy:workShopPage.groupName': 'Nombre de Grupo',
        'academy:workShopPage.groupType.solid': 'Grupo sólido',
        'academy:workShopPage.groupType.stable': 'Grupo fijo',
        'academy:workShopPage.groupType.morph': 'Grupo Anomórfico',
        'common:menu.home': 'inicio',
        'common:menu.mecuate': 'Mecuate',
        'common:menu.account': 'Mi Cuenta',
        'common:menu.academy': 'Academia',
        'common:menu.services': 'Servicios',
        'common:menu.docuweb': 'DocuWeb',
        'common:menu.projects': 'Proyectos',
        'common:menu.publications': 'Publicaciones',
        'common:menu.contact': 'Contacto',
        'common:menu.production': 'Producción',
        'common:sections.previousWorkShops': 'Previos',
        'common:sections.nextWorkShops': 'Proximos',
        'common:sections.currentWorkShops': 'Actuales',
        'common:sections.blog': 'Otros medios',
    },
    ko: {
        'academy:frontPage.title': 'Bienvenido a la Academia mecuate astrophytum',
        'academy:frontPage.description': 'this academy is made for all peoples from anywhrer in the universe.',
        'academy:workShopPage.groupName': 'Nombre de Grupo',
        'academy:workShopPage.groupType.solid': 'Grupo sólido',
        'academy:workShopPage.groupType.stable': 'Grupo fijo',
        'academy:workShopPage.groupType.morph': 'Grupo Anomórfico',
        'common:menu.home': '집',
        'common:menu.mecuate': '메큐에이트',
        'common:menu.account': '내 계정',
        'common:menu.academy': '학원',
        'common:menu.services': '서비스',
        'common:menu.docuweb': '도큐웹',
        'common:menu.projects': '프로젝트',
        'common:menu.publications': '게시',
        'common:menu.contact': '접촉',
        'common:menu.production': '생산',
        'common:sections.previousWorkShops': '이전의',
        'common:sections.nextWorkShops': '다음에 컴밍',
        'common:sections.currentWorkShops': '전류',
        'common:sections.blog': '학술 간행물 다른 미디어',
    },
}

export type iKeyTranslations =
    | 'academy:frontPage.title'
    | 'academy:frontPage.description'
    | 'academy:workShopPage.groupName'
    | 'academy:workShopPage.groupType.solid'
    | 'academy:workShopPage.groupType.stable'
    | 'academy:workShopPage.groupType.morph'
    | 'common:menu.home'
    | 'common:menu.mecuate'
    | 'common:menu.account'
    | 'common:menu.academy'
    | 'common:menu.services'
    | 'common:menu.docuweb'
    | 'common:menu.projects'
    | 'common:menu.publications'
    | 'common:menu.contact'
    | 'common:menu.production'
    | 'common:sections.previousWorkShops'
    | 'common:sections.nextWorkShops'
    | 'common:sections.currentWorkShops'
    | 'common:sections.blog'

export type LangKeys = keyof typeof validTranslationKeys
