#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch_name="$(git rev-parse --abbrev-ref HEAD)"
n=$'\n'

# FRONT END PROTOCOLS

# yarn mk.keys
# yarn format
# yarn test
# yarn typecheck


# TERMINATION
printf '\e[1;35m%s\e[0m%b' "$branch_name" " is updated. $n$n"
