name: pr-pipeline
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  prepare:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
  
    steps:
      - name: fail on draft
        if: github.event.pull_request.draft == true
        run: echo "avoid is draft" && exit 1
      - name: success
        run: echo "continue with pipeline"

  checkbranch:
    needs: prepare
    name: checking branch before merge
    runs-on: ubuntu-20.04
    container: node:lts-alpine
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: check types
        run: yarn typecheck
      - name: run unit tests
        run: yarn test
